travis:
  secure:
    BINSTAR_TOKEN: M/9Y5Nqu90P8ur/fg89g0T0NVbxOcZCSkpyAqV1eMEBkWd47oXW2AP8QmMGrukAhrqx4u4aIIg2mdcMFKUzbFsTWkRMhLfak/I6KVyFd6+7I1qeVKZdTxrg0uLc9/kSsmWDMDsLLXfCebTxDpDg2YLBGZi/FM26prSNLFMQt8T5cqBGh0nXlGKSbdXMwM26Z3W505aKrhKIttwXCTohfFbmONKaZufmk0CxCouyXESKbrROHNLmnNeRzwcbTS3a9X/pTvo3dupnqmm8L0zYL+YyoxnAyskAa/sIpf/DlIL6Oo6PCsX0/G93D06DcWeJ+qmONVh1TM3sBLvD3ZBNB7R6Xzd5ZTupPQNImB/oeQYHA0RQIQJRs6/zJ4PXsziAkq44JjHjELDPAgCrgC1AKD3OqmZ1a6/Dz3a4Bb6cUNeKaLGZPmeyGDz5QPa/eFyvkSNZHQsBWCXj8FWl/fh1FQUYJLU6QA5XNUj7FGE8DH1U6TTgqfuNd6wtPTbNuAopI7reeLl/GmfPBfJAzW4SKCKoRC4qKwCWF+LSDQQcgt6j/ySZ0VeyRVkJLctcziyylpOZ1LRBjVLoRgrc+uWsJzQveieNTzcnu/jjcjjt8upEX5mHWZ3iVDn+u97HSN7osQg7eotSMQ1Rt8jURU9iL2V8NkifB91sPgHeJF/4ncRE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
